"""phase3_inventory_movements

Revision ID: fb475d91443e
Revises: 686c3bcd48eb
Create Date: 2025-12-21 07:44:07.573547

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fb475d91443e'
down_revision: str | None = '686c3bcd48eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin_movements',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('bin_content_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False, comment='Positive for receipt, negative for issue'),
    sa.Column('quantity_before', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('fefo_compliant', sa.Boolean(), nullable=True, comment='Only for issue movements'),
    sa.Column('force_override', sa.Boolean(), nullable=False, comment='True if non-FEFO issue with manager approval'),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("movement_type IN ('receipt', 'issue', 'adjustment', 'transfer', 'scrap')", name='check_movement_type'),
    sa.ForeignKeyConstraint(['bin_content_id'], ['bin_contents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movements_bin_content', 'bin_movements', ['bin_content_id', 'created_at'], unique=False)
    op.create_index('idx_movements_created', 'bin_movements', ['created_at'], unique=False)
    op.create_index('idx_movements_type', 'bin_movements', ['movement_type', 'created_at'], unique=False)
    op.create_index('idx_movements_user', 'bin_movements', ['created_by', 'created_at'], unique=False)
    op.drop_table('bin_history')
    op.add_column('bin_contents', sa.Column('batch_number', sa.String(length=100), nullable=False))
    op.add_column('bin_contents', sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('bin_contents', sa.Column('unit', sa.String(length=50), nullable=False))
    op.add_column('bin_contents', sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bin_contents', sa.Column('received_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('bin_contents', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('bin_contents', 'pallet_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('bin_contents_bin_id_key'), 'bin_contents', type_='unique')
    op.create_index('idx_bin_contents_bin', 'bin_contents', ['bin_id'], unique=False)
    op.create_index('idx_bin_contents_expiry', 'bin_contents', ['use_by_date'], unique=False)
    op.create_index('idx_bin_contents_product_status', 'bin_contents', ['product_id', 'status', 'use_by_date'], unique=False)
    op.drop_column('bin_contents', 'delivery_date')
    op.drop_column('bin_contents', 'cmr_number')
    op.drop_column('bin_contents', 'net_weight')
    op.drop_column('bin_contents', 'gross_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bin_contents', sa.Column('gross_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('bin_contents', sa.Column('net_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('bin_contents', sa.Column('cmr_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('bin_contents', sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index('idx_bin_contents_product_status', table_name='bin_contents')
    op.drop_index('idx_bin_contents_expiry', table_name='bin_contents')
    op.drop_index('idx_bin_contents_bin', table_name='bin_contents')
    op.create_unique_constraint(op.f('bin_contents_bin_id_key'), 'bin_contents', ['bin_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('bin_contents', 'pallet_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bin_contents', 'status')
    op.drop_column('bin_contents', 'received_date')
    op.drop_column('bin_contents', 'weight_kg')
    op.drop_column('bin_contents', 'unit')
    op.drop_column('bin_contents', 'quantity')
    op.drop_column('bin_contents', 'batch_number')
    op.create_table('bin_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bin_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bin_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('pallet_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('net_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gross_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('best_before_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('freeze_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('use_by_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('cmr_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('removal_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('removal_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('removed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('removed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('bin_history_product_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('bin_history_supplier_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('bin_history_pkey'))
    )
    op.drop_index('idx_movements_user', table_name='bin_movements')
    op.drop_index('idx_movements_type', table_name='bin_movements')
    op.drop_index('idx_movements_created', table_name='bin_movements')
    op.drop_index('idx_movements_bin_content', table_name='bin_movements')
    op.drop_table('bin_movements')
    # ### end Alembic commands ###
