"""add_bin_content_receipt_fields

Revision ID: a8f4279715a7
Revises: 202af48e6f7e
Create Date: 2025-12-29 04:36:20.633886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f4279715a7'
down_revision: Union[str, None] = '202af48e6f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bin_contents', sa.Column('gross_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bin_contents', sa.Column('pallet_height_cm', sa.Integer(), nullable=True))
    op.add_column('bin_contents', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.add_column('bin_contents', sa.Column('cmr_number', sa.String(length=100), nullable=True))
    op.create_index('idx_bin_contents_cmr', 'bin_contents', ['cmr_number'], unique=False)

    # Add check constraints
    op.create_check_constraint(
        'check_positive_pallet_height',
        'bin_contents',
        'pallet_height_cm > 0 OR pallet_height_cm IS NULL'
    )
    op.create_check_constraint(
        'check_gross_weight_ge_net_weight',
        'bin_contents',
        'gross_weight_kg >= weight_kg OR gross_weight_kg IS NULL OR weight_kg IS NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop check constraints first
    op.drop_constraint('check_gross_weight_ge_net_weight', 'bin_contents', type_='check')
    op.drop_constraint('check_positive_pallet_height', 'bin_contents', type_='check')

    op.drop_index('idx_bin_contents_cmr', table_name='bin_contents')
    op.drop_column('bin_contents', 'cmr_number')
    op.drop_column('bin_contents', 'delivery_date')
    op.drop_column('bin_contents', 'pallet_height_cm')
    op.drop_column('bin_contents', 'gross_weight_kg')
    # ### end Alembic commands ###
