"""add_bin_archival_fields

Revision ID: 1b186ead5457
Revises: a8f4279715a7
Create Date: 2025-12-29 18:08:33.153376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1b186ead5457'
down_revision: Union[str, None] = 'a8f4279715a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('bins', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bins', sa.Column('archived_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('bins', sa.Column('archive_reason', sa.Text(), nullable=True))
    op.create_foreign_key('fk_bins_archived_by', 'bins', 'users', ['archived_by'], ['id'], ondelete='SET NULL')
    op.create_index('idx_bins_archived', 'bins', ['is_archived', 'warehouse_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bins_archived', table_name='bins')
    op.drop_constraint('fk_bins_archived_by', 'bins', type_='foreignkey')
    op.drop_column('bins', 'archive_reason')
    op.drop_column('bins', 'archived_by')
    op.drop_column('bins', 'archived_at')
    op.drop_column('bins', 'is_archived')
    # ### end Alembic commands ###
